{% set data = load_setup_py_data() %}

package:
    name: dusqlite
    version: {{ data['version'] }}

source:
    path: ./

requirements:
    build:
        - {{ compiler('c') }}
        - sqlite
    host:
        - python >3.5
        - pip
    run:
        - python
        - sqlalchemy
        - pandas
        - tqdm
        - ncdu
        - alembic
        - pyyaml
        - jsonschema

build:
    noarch: python
    script: 
        - "${CC} ${CFLAGS} -fPIC -shared src/dusqlite/closure.c -o src/dusqlite/closure.so"
        - "{{ PYTHON }} -m pip install . -vv"

test:
    files:
        - test/**/*.py
        - src/**/*.py
        - setup.cfg
    requires:
        - pytest
        - pytest-cov
    commands:
        - py.test --cov dusqlite
        - coverage combine .coverage
        - coverage xml -o {{ environ.get('PWD','') }}/coverage.xml
        - dusqlite --help

about:
    home: {{ data['url'] }}
    summary: {{ data['description'] }}
    license: APACHE
    license_file: LICENSE


